# Generated by Django 5.1 on 2025-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('fecha_registro', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('comentarios', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
