# Generated by Django 5.1 on 2025-11-07 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Entrenamiento_Canino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id_perro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('color', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perros', to='app_Entrenamiento_Canino.cliente')),
            ],
        ),
    ]
